title: DFSort Training Ground
author: Bard Doster
email: nunya@bizness.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is only for a training session.

# social links
twitter_username: @sucka
github_username:  not_my_username

show_excerpts: true # set to false to remove excerpts on the homepage
